// Fallback static workout and meal data for when OpenAI API is unavailable
import type { WorkoutDay, MealPlanDay } from '../types';

export const FALLBACK_WORKOUT_PLAN: WorkoutDay[] = [
    // WEEK 1
    {
        day: 1, isRestDay: false, theme: 'Full Body Activation',
        duration: 30, caloriesBurned: 200,
        motivationalNote: 'You showed up today. That\'s already a win! 💪',
        exercises: [
            {
                id: 'w1', name: 'Suryanamaskar', type: 'warm-up',
                sets: 1, reps: '5 rounds', durationSeconds: 300,
                targetMuscles: ['Full Body', 'Spine', 'Core'],
                instructions: [
                    'Stand tall at the front of your mat, feet together, palms in prayer position.',
                    'Inhale deeply and raise your arms overhead, gently arch back.',
                    'Exhale and fold forward, bringing your hands to the floor.',
                    'Inhale, step your right foot back into a lunge, look up.',
                    'Hold plank position for a breath, then lower to floor in Chaturanga.',
                    'Inhale into Upward Dog or Cobra, then exhale into Downward Dog.',
                    'Step feet forward, inhale halfway lift, exhale fold completely.',
                    'Inhale, rise up with arms overhead, exhale return to prayer. Repeat.',
                ],
                commonMistakes: ['Holding breath', 'Locking knees in forward fold', 'Sagging hips in plank'],
                beginnerModification: 'Do the flow slowly, skip Chaturanga — lower knees to floor instead.',
                advancedVariation: 'Increase rounds to 12. Add a jump-back into plank.',
                gifKeyword: 'suryanamaskar yoga',
            },
            {
                id: 'w2', name: 'Bodyweight Squats', type: 'strength',
                sets: 3, reps: '15', durationSeconds: 180,
                targetMuscles: ['Quads', 'Glutes', 'Hamstrings'],
                instructions: [
                    'Stand with feet shoulder-width apart, toes slightly outward.',
                    'Keep chest proud, core braced, and arms extended forward for balance.',
                    'Push hips back and bend knees, lowering until thighs are parallel to floor.',
                    'Press through your heels to return to standing.',
                    'Squeeze glutes at the top of each rep.',
                ],
                commonMistakes: ['Knees caving inward', 'Heels lifting off floor', 'Rounding lower back'],
                beginnerModification: 'Squat to a chair seat for guidance and support.',
                advancedVariation: 'Add a jump at the top — jump squats.',
                gifKeyword: 'bodyweight squat',
            },
            {
                id: 'w3', name: 'Knee Push-Ups', type: 'strength',
                sets: 3, reps: '10', durationSeconds: 150,
                targetMuscles: ['Chest', 'Triceps', 'Shoulders'],
                instructions: [
                    'Start on hands and knees, hands slightly wider than shoulders.',
                    'Lower your chest to the floor, keeping elbows at 45° to body.',
                    'Press back up to starting position, fully extending arms.',
                    'Keep core tight throughout — don\'t let hips sag.',
                    'Breathe in as you lower, out as you push up.',
                ],
                commonMistakes: ['Flaring elbows wide', 'Looking forward instead of down', 'Moving too fast'],
                beginnerModification: 'Wall push-ups are even gentler for beginners.',
                advancedVariation: 'Progress to full push-ups or diamond push-ups.',
                gifKeyword: 'knee push up',
            },
            {
                id: 'w4', name: 'Standing Forward Bend', type: 'cool-down',
                sets: 1, reps: '60 seconds', durationSeconds: 60,
                targetMuscles: ['Hamstrings', 'Back', 'Calves'],
                instructions: [
                    'Stand with feet hip-width apart.',
                    'Exhale and hinge forward from the hips, not the waist.',
                    'Let your head hang heavy, arms dangle or hold elbows.',
                    'Bend knees slightly if hamstrings are tight.',
                    'Breathe deeply and feel the gentle stretch with each exhale.',
                ],
                commonMistakes: ['Rounding back instead of hinging hips', 'Locking knees'],
                beginnerModification: 'Bend knees generously and rest hands on shins.',
                advancedVariation: 'Walk hands forward for a deeper stretch.',
                gifKeyword: 'standing forward bend yoga',
            },
        ],
    },
    {
        day: 2, isRestDay: false, theme: 'Core & Posture',
        duration: 30, caloriesBurned: 180,
        motivationalNote: 'Day 2! Your consistency is already building something beautiful 🌸',
        exercises: [
            {
                id: 'c1', name: 'Suryanamaskar', type: 'warm-up',
                sets: 1, reps: '5 rounds', durationSeconds: 300,
                targetMuscles: ['Full Body'],
                instructions: ['Repeat the same sun salutation flow from Day 1. Move with your breath. Each round should feel more fluid than the last.'],
                commonMistakes: ['Rushing through the sequence'],
                beginnerModification: 'Slow it down — quality over speed.',
                advancedVariation: '8 rounds at a steady pace.',
                gifKeyword: 'suryanamaskar',
            },
            {
                id: 'c2', name: 'Plank Hold', type: 'strength',
                sets: 3, reps: '30 seconds', durationSeconds: 180,
                targetMuscles: ['Core', 'Shoulders', 'Glutes'],
                instructions: [
                    'Start in a push-up position — hands under shoulders, body in a straight line.',
                    'Squeeze your core muscles like you\'re bracing for a punch.',
                    'Press the floor away with your hands — don\'t let shoulders creep to ears.',
                    'Keep hips level — neither sagging nor piking up.',
                    'Breathe steadily. Hold for the full 30 seconds.',
                ],
                commonMistakes: ['Holding breath', 'Hips too high or too low', 'Neck straining down'],
                beginnerModification: 'Forearm plank or knees-down plank.',
                advancedVariation: 'Extend hold to 60 seconds or add shoulder taps.',
                gifKeyword: 'plank hold',
            },
            {
                id: 'c3', name: 'Bicycle Crunches', type: 'strength',
                sets: 3, reps: '20 (10 each side)', durationSeconds: 150,
                targetMuscles: ['Obliques', 'Core', 'Hip Flexors'],
                instructions: [
                    'Lie on your back, hands behind head (don\'t pull neck), knees bent.',
                    'Lift shoulders off the floor and bring left knee to chest.',
                    'Simultaneously twist right elbow toward left knee.',
                    'Extend left leg as right knee comes in and left elbow twists toward it.',
                    'Continue alternating in a smooth cycling motion.',
                ],
                commonMistakes: ['Pulling on the neck', 'Moving elbows instead of twisting torso', 'Going too fast'],
                beginnerModification: 'Keep feet on the floor and do a simpler side crunch.',
                advancedVariation: 'Slow down each rep to 2 seconds each side for maximum engagement.',
                gifKeyword: 'bicycle crunch',
            },
            {
                id: 'c4', name: 'Childs Pose', type: 'cool-down',
                sets: 1, reps: '90 seconds', durationSeconds: 90,
                targetMuscles: ['Back', 'Hips', 'Shoulders'],
                instructions: [
                    'Kneel on the floor, big toes touching, knees hip-width apart.',
                    'Exhale and lower your torso between your thighs.',
                    'Extend arms forward or rest them along your sides.',
                    'Rest your forehead gently on the mat.',
                    'Breathe deeply into your back — let every exhale release tension.',
                ],
                commonMistakes: ['Holding tension in shoulders'],
                beginnerModification: 'Place a pillow under your forehead for support.',
                advancedVariation: 'Walk hands further forward to deepen the shoulder stretch.',
                gifKeyword: "child's pose yoga",
            },
        ],
    },
    {
        day: 3, isRestDay: false, theme: 'Lower Body Burn',
        duration: 30, caloriesBurned: 220,
        motivationalNote: 'Three days in! Your legs are getting stronger with every step 🌿',
        exercises: [
            {
                id: 'l1', name: 'Suryanamaskar', type: 'warm-up',
                sets: 1, reps: '5 rounds', durationSeconds: 300,
                targetMuscles: ['Full Body'],
                instructions: ['Flow through 5 sun salutations to warm the body. Focus on deep breathing.'],
                commonMistakes: ['Forgetting to breathe'],
                beginnerModification: 'Take breaks between rounds.',
                advancedVariation: 'Increase pace slightly.',
                gifKeyword: 'suryanamaskar',
            },
            {
                id: 'l2', name: 'Reverse Lunges', type: 'strength',
                sets: 3, reps: '12 each leg', durationSeconds: 180,
                targetMuscles: ['Glutes', 'Quads', 'Hamstrings'],
                instructions: [
                    'Stand tall with feet hip-width apart, hands on hips.',
                    'Step your right foot backward and lower your right knee toward the floor.',
                    'Front knee should stay above ankle — not jutting forward.',
                    'Press through your left heel to return to standing.',
                    'Complete all reps on one side before switching.',
                ],
                commonMistakes: ['Front knee caving inward', 'Leaning torso forward', 'Back knee slamming the floor'],
                beginnerModification: 'Hold a wall for balance. Reduce depth of lunge.',
                advancedVariation: 'Add a knee drive as you return to standing.',
                gifKeyword: 'reverse lunge',
            },
            {
                id: 'l3', name: 'Glute Bridges', type: 'strength',
                sets: 3, reps: '20', durationSeconds: 180,
                targetMuscles: ['Glutes', 'Hamstrings', 'Core'],
                instructions: [
                    'Lie on your back with knees bent, feet flat on floor, hip-width apart.',
                    'Press arms flat on the floor by your sides.',
                    'Press your heels into the floor and squeeze your glutes to lift your hips.',
                    'Form a straight line from knees to shoulders at the top.',
                    'Slowly lower back down — don\'t just drop!',
                ],
                commonMistakes: ['Pushing through toes instead of heels', 'Not fully extending at top', 'Hyperextending lower back'],
                beginnerModification: 'Smaller range of motion, focus on squeezing glutes.',
                advancedVariation: 'Single-leg glute bridge. Add a resistance band above knees.',
                gifKeyword: 'glute bridge',
            },
            {
                id: 'l4', name: 'Seated Forward Fold', type: 'cool-down',
                sets: 1, reps: '90 seconds', durationSeconds: 90,
                targetMuscles: ['Hamstrings', 'Lower Back'],
                instructions: [
                    'Sit on the floor with legs extended straight in front of you.',
                    'Flex your feet — toes point toward the ceiling.',
                    'Inhale, lengthen your spine tall.',
                    'Exhale, fold forward from the hips, reaching for your feet or shins.',
                    'Hold and breathe deeply — let each exhale deepen the fold.',
                ],
                commonMistakes: ['Rounding back instead of hinging forward'],
                beginnerModification: 'Use a yoga strap or towel around feet.',
                advancedVariation: 'Reach past feet and hold ankles.',
                gifKeyword: 'seated forward fold yoga',
            },
        ],
    },
    {
        day: 4, isRestDay: false, theme: 'Upper Body & Arms', duration: 30, caloriesBurned: 190,
        motivationalNote: 'Building strength in your arms means carrying life with ease 💪',
        exercises: [
            {
                id: 'u1', name: 'Suryanamaskar', type: 'warm-up',
                sets: 1, reps: '5 rounds', durationSeconds: 300, targetMuscles: ['Full Body'],
                instructions: ['5 fluid rounds to warm up. Focus on engaging your arms fully.'],
                commonMistakes: ['Rushing'], beginnerModification: 'Slow pace.', advancedVariation: '8 rounds.',
                gifKeyword: 'suryanamaskar',
            },
            {
                id: 'u2', name: 'Push-Ups', type: 'strength',
                sets: 3, reps: '8–12', durationSeconds: 180, targetMuscles: ['Chest', 'Triceps', 'Shoulders'],
                instructions: [
                    'Full push-up position — hands shoulder-width, body straight.',
                    'Lower chest to floor keeping elbows at 45°.',
                    'Push back up explosively.',
                    'Keep core tight throughout.',
                    'Breathe in down, out up.',
                ],
                commonMistakes: ['Flaring elbows', 'Sagging hips'],
                beginnerModification: 'Knee push-ups.', advancedVariation: 'Slow 4-count descent.',
                gifKeyword: 'push up',
            },
            {
                id: 'u3', name: 'Tricep Dips (Chair)', type: 'strength',
                sets: 3, reps: '12', durationSeconds: 150, targetMuscles: ['Triceps', 'Shoulders'],
                instructions: [
                    'Sit on the edge of a sturdy chair, hands gripping the seat beside hips.',
                    'Slide your bottom off the chair, legs extended or bent.',
                    'Bend elbows to lower body toward the floor.',
                    'Straighten arms to press back up.',
                    'Keep back close to chair.',
                ],
                commonMistakes: ['Shoulders shrugging', 'Bending from the waist'],
                beginnerModification: 'Keep knees bent at 90°.', advancedVariation: 'Extend legs straight.',
                gifKeyword: 'tricep dips chair',
            },
            {
                id: 'u4', name: 'Thread the Needle Stretch', type: 'cool-down',
                sets: 1, reps: '60 seconds each side', durationSeconds: 120, targetMuscles: ['Shoulders', 'Upper Back'],
                instructions: [
                    'Start on hands and knees in tabletop position.',
                    'Slide your right arm under your body to the left, palm facing up.',
                    'Let your right shoulder and ear rest on the floor.',
                    'Hold for 60 seconds, breathing deeply.',
                    'Repeat on the other side.',
                ],
                commonMistakes: ['Twisting from waist instead of thoracic spine'],
                beginnerModification: 'Less rotation.', advancedVariation: 'Reach top arm overhead.',
                gifKeyword: 'thread the needle stretch',
            },
        ],
    },
    {
        day: 5, isRestDay: false, theme: 'Cardio Dance & Fun', duration: 30, caloriesBurned: 240,
        motivationalNote: 'Dance like nobody\'s watching — because you\'re doing it for YOU! 💃',
        exercises: [
            {
                id: 'd1', name: 'Suryanamaskar', type: 'warm-up',
                sets: 1, reps: '5 rounds', durationSeconds: 300, targetMuscles: ['Full Body'],
                instructions: ['5 rounds to warm up. Let your body flow freely.'],
                commonMistakes: ['Holding breath'], beginnerModification: 'Slow pace.', advancedVariation: 'Faster pace.',
                gifKeyword: 'suryanamaskar',
            },
            {
                id: 'd2', name: 'Bhangra Steps', type: 'cardio',
                sets: 3, reps: '2 minutes', durationSeconds: 360, targetMuscles: ['Full Body', 'Cardio'],
                instructions: [
                    'Stand with feet slightly wider than hip-width, arms out to sides.',
                    'Step right foot out to right, arms raise—right arm up, left arm out.',
                    'Bring left foot to meet right, swap arms.',
                    'Add a shoulder shimmy and hip pop for the authentic Bhangra feel!',
                    'Move continuously, keep energy HIGH!',
                ],
                commonMistakes: ['Moving too small — big arm movements are the point!'],
                beginnerModification: 'Slower pace, less arm movement.', advancedVariation: 'Add jumps and kicks.',
                gifKeyword: 'bhangra dance steps',
            },
            {
                id: 'd3', name: 'Mountain Climbers', type: 'cardio',
                sets: 3, reps: '30 seconds', durationSeconds: 150, targetMuscles: ['Core', 'Cardio', 'Shoulders'],
                instructions: [
                    'Start in high plank position, arms straight.',
                    'Drive right knee toward chest, then quickly switch to left.',
                    'Keep hips level — don\'t let them bounce.',
                    'Move as fast as you can while maintaining form.',
                    'Breathe steadily.',
                ],
                commonMistakes: ['Hips shooting up', 'Looking down'],
                beginnerModification: 'Slow mountain climbers — step instead of run.', advancedVariation: 'Cross-body mountain climbers.',
                gifKeyword: 'mountain climbers exercise',
            },
            {
                id: 'd4', name: 'Supine Twist', type: 'cool-down',
                sets: 1, reps: '60 seconds each side', durationSeconds: 120, targetMuscles: ['Spine', 'Hips', 'Back'],
                instructions: [
                    'Lie on your back with arms out in a T shape.',
                    'Draw right knee to chest, then let it fall to the left.',
                    'Turn your head to the right, opposite direction of the knee.',
                    'Breathe deeply and relax into the twist.',
                    'Switch sides after 60 seconds.',
                ],
                commonMistakes: ['Forcing the twist', 'Lifting shoulders off floor'],
                beginnerModification: 'Keep both knees bent together.', advancedVariation: 'Extend the top leg straight.',
                gifKeyword: 'supine spinal twist yoga',
            },
        ],
    },
    {
        day: 6, isRestDay: true, theme: 'Rest & Recover', duration: 0, caloriesBurned: 0,
        motivationalNote: 'Rest is not laziness — it\'s growth. Your muscles are rebuilding today! 💖',
        exercises: [],
    },
    // Days 7-30 follow similar structure but progressively harder
    ...generateRemainingDays(),
];

function generateRemainingDays(): WorkoutDay[] {
    const themes = [
        'Strength Foundation', 'Yoga Flow', 'Full Body Circuit', 'Core Power',
        'Lower Body Strength', 'Cardio Blast', 'Upper Body Sculpt', 'Flexibility & Balance',
        'HIIT Power', 'Active Recovery Yoga', 'Push Day', 'Pull Day',
        'Leg Day', 'Cardio Dance', 'Full Body Strength', 'Core & Stability',
        'Glute Focus', 'Shoulder & Arms', 'Cardio & Core', 'Yoga & Breathwork',
        'Peak Week: Full Body', 'Peak Week: Cardio Max', 'Peak Week: Strength Max', 'Peak Week: Finisher',
    ];

    const days: WorkoutDay[] = [];
    for (let i = 7; i <= 30; i++) {
        const isRest = i % 6 === 0;
        const themeIndex = (i - 7) % themes.length;
        const weekMultiplier = Math.floor((i - 1) / 7) + 1;
        days.push({
            day: i,
            isRestDay: isRest,
            theme: isRest ? 'Rest & Recover' : themes[themeIndex],
            duration: isRest ? 0 : 30,
            caloriesBurned: isRest ? 0 : 180 + weekMultiplier * 15,
            motivationalNote: isRest
                ? 'Rest well, warrior. Tomorrow you come back stronger! 🌙'
                : `Day ${i}! Week ${weekMultiplier} progress. Keep going! 💪`,
            exercises: isRest ? [] : [
                {
                    id: `ex${i}-1`, name: 'Suryanamaskar', type: 'warm-up',
                    sets: 1, reps: `${5 + weekMultiplier} rounds`, durationSeconds: 300 + weekMultiplier * 30,
                    targetMuscles: ['Full Body'],
                    instructions: ['Flow through sun salutations at a comfortable pace. Breathe deeply.'],
                    commonMistakes: ['Rushing'], beginnerModification: 'Fewer rounds.', advancedVariation: 'More rounds.',
                    gifKeyword: 'suryanamaskar',
                },
                {
                    id: `ex${i}-2`, name: 'Squats', type: 'strength',
                    sets: 3, reps: `${12 + weekMultiplier * 2}`, durationSeconds: 180,
                    targetMuscles: ['Quads', 'Glutes', 'Hamstrings'],
                    instructions: ['Perform bodyweight squats with perfect form. Squeeze glutes at top.'],
                    commonMistakes: ['Knees caving in'], beginnerModification: 'Chair squats.', advancedVariation: 'Jump squats.',
                    gifKeyword: 'squat',
                },
                {
                    id: `ex${i}-3`, name: 'Plank', type: 'strength',
                    sets: 3, reps: `${30 + weekMultiplier * 10} sec`, durationSeconds: 150,
                    targetMuscles: ['Core', 'Shoulders'],
                    instructions: ['Hold a strong plank. Core tight, hips level.'],
                    commonMistakes: ['Sagging hips'], beginnerModification: 'Forearm plank.', advancedVariation: 'Side plank.',
                    gifKeyword: 'plank hold',
                },
                {
                    id: `ex${i}-4`, name: 'Childs Pose', type: 'cool-down',
                    sets: 1, reps: '90 seconds', durationSeconds: 90,
                    targetMuscles: ['Back', 'Hips'],
                    instructions: ['Rest in child\'s pose, breathing deeply into your back.'],
                    commonMistakes: ['Holding tension'], beginnerModification: 'Pillow under forehead.', advancedVariation: 'Extended arms.',
                    gifKeyword: "child's pose",
                },
            ],
        });
    }
    return days;
}

export const FALLBACK_MEAL_PLAN: MealPlanDay[] = [
    {
        day: 1,
        meals: {
            breakfast: {
                name: 'Moong Dal Cheela with Green Chutney',
                time: '7:00–8:00 AM',
                calories: 320, protein: 18, carbs: 42, fat: 8,
                prepTime: '20 min',
                ingredients: ['1 cup moong dal (soaked, ground)', '1 onion (chopped)', '1 green chilli', 'Coriander leaves', 'Salt, cumin'],
                instructions: 'Blend soaked moong dal with spices. Pour thin batter on non-stick pan. Cook until golden on both sides.',
                tip: 'Pair with mint chutney for gut health benefits. Rich in complete protein.',
                tags: ['PCOS Friendly', 'High Protein'],
            },
            midMorningSnack: {
                name: 'Mixed Fruit Chaat',
                time: '10:30 AM',
                calories: 120, protein: 2, carbs: 28, fat: 1,
                prepTime: '5 min',
                ingredients: ['1 banana', '1 apple', 'Few grapes', 'Chaat masala', 'Lime juice'],
                instructions: 'Chop fruits, toss with chaat masala and lime. Serve fresh.',
                tip: 'Eat fruits on an empty stomach for best digestion.',
                tags: ['Thyroid Friendly'],
            },
            lunch: {
                name: 'Dal Tadka + 2 Phulka + Sabzi + Dahi',
                time: '1:00–2:00 PM',
                calories: 520, protein: 24, carbs: 72, fat: 12,
                prepTime: '30 min',
                ingredients: ['1 katori toor dal', '2 phulka (whole wheat)', '1 katori sabzi', '1 katori dahi', 'Ghee (1 tsp)', 'Jeera, hing, turmeric'],
                instructions: 'Cook dal with turmeric. Prepare tadka with ghee, jeera, hing, tomato. Pair with seasonal sabzi and fresh dahi.',
                tip: 'Adding hing to dal improves digestibility and reduces gas.',
                tags: ['Balanced Meal', 'PCOS Friendly'],
            },
            eveningSnack: {
                name: 'Roasted Makhana (Fox Nuts)',
                time: '4:30–5:00 PM',
                calories: 110, protein: 4, carbs: 18, fat: 3,
                prepTime: '10 min',
                ingredients: ['1 cup makhana', '½ tsp ghee', 'Rock salt', 'Black pepper'],
                instructions: 'Dry roast makhana in a pan or oven. Add a tiny dot of ghee, rock salt, and pepper.',
                tip: 'Makhana is low GI and excellent for PCOS and thyroid. Great post-workout snack.',
                tags: ['PCOS Friendly', 'Low Calorie'],
            },
            dinner: {
                name: 'Palak Paneer + 1 Roti + Salad',
                time: '7:30–8:00 PM',
                calories: 380, protein: 22, carbs: 38, fat: 14,
                prepTime: '25 min',
                ingredients: ['100g paneer', '2 cups palak (spinach)', '1 roti (whole wheat)', '1 onion-tomato-cucumber salad', 'Spices, ginger, garlic'],
                instructions: 'Purée blanched spinach. Cook with spices, add paneer cubes. Serve with 1 phulka and fresh salad.',
                tip: 'Add a squeeze of lime to palak paneer — it helps absorb the iron from spinach.',
                tags: ['High Protein', 'Iron Rich'],
            },
        },
    },
    {
        day: 2,
        meals: {
            breakfast: {
                name: 'Oats Dalia with Nuts & Seeds',
                time: '7:00–8:00 AM',
                calories: 290, protein: 10, carbs: 46, fat: 9,
                prepTime: '10 min',
                ingredients: ['½ cup broken wheat dalia or oats', '1 tbsp mixed nuts', '1 tsp flaxseeds', '1 cup milk or water'],
                instructions: 'Cook dalia or oats in milk. Top with chopped nuts, seeds, and optional honey.',
                tip: 'Flaxseeds are excellent for managing PCOS symptoms and hormonal balance.',
                tags: ['PCOS Friendly', 'Heart Healthy'],
            },
            midMorningSnack: {
                name: 'Buttermilk (Chaas)',
                time: '10:30 AM',
                calories: 60, protein: 3, carbs: 8, fat: 1,
                prepTime: '2 min',
                ingredients: ['1 cup curd', 'Water', 'Jeera powder', 'Kala namak', 'Coriander'],
                instructions: 'Blend curd with water and spices. Serve chilled.',
                tip: 'Chaas improves gut health and keeps you full between meals.',
                tags: ['Gut Friendly', 'Low Calorie'],
            },
            lunch: {
                name: 'Rajma Chawal + Kachumber Salad',
                time: '1:00–2:00 PM',
                calories: 480, protein: 20, carbs: 80, fat: 8,
                prepTime: '35 min',
                ingredients: ['1 katori rajma (cooked)', '¾ cup brown rice', 'Tomato, onion gravy', 'Kachumber: cucumber, tomato, onion, lime'],
                instructions: 'Cook rajma in pressure cooker with spices. Serve over rice with fresh kachumber salad.',
                tip: 'Rajma is one of the richest plant-based protein sources. Use brown rice for better glycemic control.',
                tags: ['Vegetarian', 'High Protein'],
            },
            eveningSnack: {
                name: 'Sprouts Chaat',
                time: '4:30–5:00 PM',
                calories: 130, protein: 8, carbs: 20, fat: 2,
                prepTime: '5 min',
                ingredients: ['1 cup mixed sprouts (moong, chana)', 'Tomato, onion', 'Chaat masala', 'Lime', 'Coriander'],
                instructions: 'Mix sprouted legumes with chopped veggies and seasonings. Enjoy immediately.',
                tip: 'Sprouting multiplies the nutrient content by 3–5x. Great pre-workout snack.',
                tags: ['High Protein', 'Thyroid Friendly'],
            },
            dinner: {
                name: 'Grilled Tofu Sabzi + Roti + Dal Soup',
                time: '7:30–8:00 PM',
                calories: 360, protein: 24, carbs: 40, fat: 10,
                prepTime: '20 min',
                ingredients: ['150g firm tofu', '1 roti', '1 bowl moong dal soup', 'Bell peppers, onion, spices'],
                instructions: 'Cube tofu, marinate with spices, grill or pan-fry. Serve with roti and warm dal soup.',
                tip: 'Tofu is a complete plant protein — ideal for vegetarians and vegans.',
                tags: ['Low Calorie', 'High Protein'],
            },
        },
    },
];

export type { WorkoutDay, MealPlanDay };
